spring:
  datasource:
    url: jdbc:postgresql://training-2022.csytydlyilnq.ap-northeast-1.rds.amazonaws.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
